name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Qodana Fix (FQN only)
        if: github.event_name == 'pull_request'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --config,qodana-fix.yaml
          results-dir: ${{ runner.temp }}/qodana-fix/results
          cache-dir: ${{ runner.temp }}/qodana-fix/cache
          push-fixes: pull-request
          pr-mode: false

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          upload-result: true
          pr-mode: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
